// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gonetmap

func ifaceTOint(i interface{}) int {
	var idx int
	switch i.(type) {
	case int:
		idx = int(i.(int))
	case int16:
		idx = int(i.(int16))
	case int32:
		idx = int(i.(int32))
	case int64:
		idx = int(i.(int64))

	case uint:
		idx = int(i.(int))
	case uint16:
		idx = int(i.(uint16))
	case uint32:
		idx = int(i.(uint32))
	case uint64:
		idx = int(i.(uint64))
	}
	return idx
}
